# Generated by Django 2.2.5 on 2019-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchTest', '0002_auto_20190908_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='post',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
