# Generated by Django 2.2.5 on 2019-09-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchTest', '0003_auto_20190908_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(auto_now=True),
        ),
    ]
