# Generated by Django 2.2.5 on 2019-09-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchTest', '0004_auto_20190908_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
