# Generated by Django 2.2.5 on 2019-09-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchTest', '0006_remove_movie_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
    ]
