# Generated by Django 2.2.5 on 2019-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchTest', '0007_remove_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='post',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(auto_now=True),
        ),
    ]
